name: BenchmarkApp
options:
  bundleIdPrefix: com.mltrain
  deploymentTarget:
    iOS: "16.0"

targets:
  BenchmarkApp:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.entitlements"
          - Info.plist
          - "*.mlpackage"
    resources:
      - path: .
        includes:
          - "*.mlpackage"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: ML Benchmark
        NSCameraUsageDescription: Camera access is required for real-time object detection.
        NSLocalNetworkUsageDescription: This app runs a local server to receive benchmark requests from your computer.
        NSBonjourServices:
          - _http._tcp
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - benchmark
    entitlements:
      path: BenchmarkApp.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mltrain.benchmarkapp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
